In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

sns.set_style("whitegrid")

In [2]:
df = pd.read_csv("../dataset/test_datafile.csv")

df.head()

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,avg_monthly_gb_used,num_support_tickets,avg_monthly_minutes,satisfaction_score,payment_method,num_additional_services,last_interaction_date,churned
0,TC-004711,32.874739,Male,10.149619,Month-to-month,69.24,656.42,DSL,Yes,11.70,4.0,324.0,7.8,bank transfer,2,2024-06-14,1
1,TC-000692,59.389947,Female,3.446551,Month-to-month,98.48,251.15,DSL,no,9.46,1.0,306.8,6.0,Electronic check,5,2024-06-23,1
2,TC-000066,62.343600,male,1.386582,Two year,94.35,120.78,Fiber optic,Yes,9.56,4.0,349.5,5.5,Bank transfer,0,2024-06-21,0
3,TC-003427,45.788533,Female,67.609659,Month-to-month,85.87,5834.73,Fiber optic,yes,3.15,1.0,258.2,4.7,Credit card,4,2024-06-21,1
4,TC-004821,39.625418,F,27.319623,One year,62.14,1626.23,DSL,Yes,28.80,0.0,335.8,12.3,Credit card,2,2024-06-19,0

In [3]:
def dataset_overview(df):
    print("=" * 60)
    print("DATASET OVERVIEW")
    print("=" * 60)

    print(f"Rows    : {df.shape[0]}")
    print(f"Columns : {df.shape[1]}")

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    display(df.dtypes)

    print("\nMissing Values:")
    display(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

dataset_overview(df)

============================================================
DATASET OVERVIEW
============================================================
Rows    : 5050
Columns : 17

Column Names:
['customer_id', 'age', 'gender', 'tenure_months', 'contract_type', 'monthly_charges', 'total_charges', 'internet_service', 'phone_service', 'avg_monthly_gb_used', 'num_support_tickets', 'avg_monthly_minutes', 'satisfaction_score', 'payment_method', 'num_additional_services', 'last_interaction_date', 'churned']

Data Types:

customer_id                    str
age                        float64
gender                         str
tenure_months              float64
contract_type                  str
monthly_charges            float64
total_charges              float64
internet_service               str
phone_service                  str
avg_monthly_gb_used        float64
num_support_tickets        float64
avg_monthly_minutes        float64
satisfaction_score         float64
payment_method                 str
num_additional_services      int64
last_interaction_date          str
churned                      int64
dtype: object

Missing Values:

customer_id                  0
age                         10
gender                      50
tenure_months               11
contract_type                0
monthly_charges             12
total_charges               23
internet_service           505
phone_service                0
avg_monthly_gb_used         15
num_support_tickets          0
avg_monthly_minutes         82
satisfaction_score          20
payment_method              30
num_additional_services      0
last_interaction_date        0
churned                      0
dtype: int64

Duplicate Rows:
50

In [4]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,5050,5000,TC-004711,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,5040.0,NaN,NaN,NaN,42.752631,24.003502,-1.0,31.978442,42.193729,52.026286,999.0
gender,5000,8,Male,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tenure_months,5039.0,NaN,NaN,NaN,24.092848,24.343918,-12.0,6.83739,16.483189,33.823095,500.0
contract_type,5050,3,Month-to-month,2822,NaN,NaN,NaN,NaN,NaN,NaN,NaN
monthly_charges,5038.0,NaN,NaN,NaN,69.921683,211.202935,-50.0,47.5325,65.05,82.25,9999.0
total_charges,5027.0,NaN,NaN,NaN,1642.31954,4183.374844,0.66,372.28,953.64,2122.525,218681.58
internet_service,4545,5,Fiber optic,1721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
phone_service,5050,6,Yes,2530,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_monthly_gb_used,5035.0,NaN,NaN,NaN,15.153484,15.601767,-86.55345,4.425,10.36,21.625,119.67
num_support_tickets,5050.0,NaN,NaN,NaN,2.270099,12.218691,-5.0,1.0,2.0,3.0,500.0
avg_monthly_minutes,4968.0,NaN,NaN,NaN,299.333394,117.937511,0.0,215.4,299.25,378.225,747.5
satisfaction_score,5030.0,NaN,NaN,NaN,6.098708,3.333432,-1.4,4.6,6.0,7.4,99.0
payment_method,5020,8,Credit card,1274,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_additional_services,5050.0,NaN,NaN,NaN,2.483366,1.711466,0.0,1.0,2.0,4.0,5.0
last_interaction_date,5050,192,2024-06-30,186,NaN,NaN,NaN,NaN,NaN,NaN,NaN
churned,5050.0,NaN,NaN,NaN,0.363762,0.481129,0.0,0.0,0.0,1.0,1.0

In [5]:
duplicate_ids = df[df["customer_id"].duplicated(keep=False)]

print(f"Duplicate Customer IDs : {duplicate_ids.shape[0]}")

duplicate_ids.head()

Duplicate Customer IDs : 100

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,avg_monthly_gb_used,num_support_tickets,avg_monthly_minutes,satisfaction_score,payment_method,num_additional_services,last_interaction_date,churned
0,TC-004711,32.874739,Male,10.149619,Month-to-month,69.24,656.42,DSL,Yes,11.70,4.0,324.0,7.8,bank transfer,2,2024-06-14,1
34,TC-001145,39.403923,M,4.400608,Two year,74.25,320.27,No,Yes,3.35,4.0,355.4,2.2,Electronic check,5,2024-06-06,0
76,TC-002787,30.450059,Male,48.480751,One year,57.37,2784.99,Fiber optic,Yes,44.94,2.0,118.9,6.8,Credit card,2,2024-02-26,0
204,TC-004940,20.998939,Male,20.145723,Month-to-month,65.60,1447.34,No,Y,7.10,2.0,271.1,2.6,Credit card,3,2024-05-26,0
301,TC-000385,30.613010,Female,69.584358,Month-to-month,69.10,4757.33,Fiber optic,Yes,13.51,3.0,52.3,5.5,Mailed check,0,2024-05-30,1

In [6]:
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing %": round((df.isnull().sum() / len(df)) * 100, 2)
})

missing = missing[missing["Missing Count"] > 0]

missing.sort_values("Missing %", ascending=False)

                     Missing Count  Missing %
internet_service               505      10.00
avg_monthly_minutes             82       1.62
gender                          50       0.99
payment_method                  30       0.59
total_charges                   23       0.46
satisfaction_score              20       0.40
avg_monthly_gb_used             15       0.30
monthly_charges                 12       0.24
tenure_months                   11       0.22
age                             10       0.20

In [7]:
pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Unique Values": df.nunique().values
})

                     Column Data Type  Unique Values
0               customer_id       str           5000
1                       age   float64           4706
2                    gender       str              8
3             tenure_months   float64           4757
4             contract_type       str              3
5           monthly_charges   float64           3740
6             total_charges   float64           4935
7          internet_service       str              5
8             phone_service       str              6
9       avg_monthly_gb_used   float64           2714
10      num_support_tickets   float64             12
11      avg_monthly_minutes   float64           2951
12       satisfaction_score   float64            130
13           payment_method       str              8
14  num_additional_services     int64              6
15    last_interaction_date       str            192
16                  churned     int64              2

In [8]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print("=" * 60)
    print(col)
    print(df[col].value_counts(dropna=False))
    print()

============================================================
customer_id
customer_id
TC-004711    2
TC-001145    2
TC-002787    2
TC-004940    2
TC-000385    2
            ..
TC-004427    1
TC-000467    1
TC-003093    1
TC-003773    1
TC-000861    1
Name: count, Length: 5000, dtype: int64

============================================================
gender
gender
Male      1751
Female    1729
F          410
M          392
female     215
MALE       203
male       202
Other       98
NaN         50
Name: count, dtype: int64

============================================================
contract_type
contract_type
Month-to-month    2822
One year          1235
Two year           993
Name: count, dtype: int64

============================================================
internet_service
internet_service
Fiber optic    1721
DSL            1278
No              736
NaN             505
fiber           440
dsl             370
Name: count, dtype: int64

============================================================
phone_service
phone_service
Yes    2530
No     1239
yes     431
no      348
N       258
Y       244
Name: count, dtype: int64

============================================================
payment_method
payment_method
Credit card         1274
Electronic check    1216
Bank transfer       1027
Mailed check         736
credit card          243
bank transfer        194
BT                   166
CC                   164
NaN                   30
Name: count, dtype: int64

============================================================
last_interaction_date
last_interaction_date
2024-06-30    186
2024-06-29    173
2024-06-27    162
2024-06-25    148
2024-06-22    142
             ...
2024-01-28      1
2024-01-20      1
2024-07-13      1
2024-01-21      1
2024-07-17      1
Name: count, Length: 192, dtype: int64

In [9]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

df[numeric_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
age,5040.0,42.752631,24.003502,-1.00000,31.978442,42.193729,52.026286,999.00
tenure_months,5039.0,24.092848,24.343918,-12.00000,6.837390,16.483189,33.823095,500.00
monthly_charges,5038.0,69.921683,211.202935,-50.00000,47.532500,65.050000,82.250000,9999.00
total_charges,5027.0,1642.319540,4183.374844,0.66000,372.280000,953.640000,2122.525000,218681.58
avg_monthly_gb_used,5035.0,15.153484,15.601767,-86.55345,4.425000,10.360000,21.625000,119.67
num_support_tickets,5050.0,2.270099,12.218691,-5.00000,1.000000,2.000000,3.000000,500.00
avg_monthly_minutes,4968.0,299.333394,117.937511,0.00000,215.400000,299.250000,378.225000,747.50
satisfaction_score,5030.0,6.098708,3.333432,-1.40000,4.600000,6.000000,7.400000,99.00
num_additional_services,5050.0,2.483366,1.711466,0.00000,1.000000,2.000000,4.000000,5.00
churned,5050.0,0.363762,0.481129,0.00000,0.000000,0.000000,1.000000,1.00

In [10]:
def check_numeric_ranges(df):
    checks = {
        "age": (0, 120),
        "tenure_months": (0, 120),
        "monthly_charges": (0, None),
        "total_charges": (0, None),
        "avg_monthly_gb_used": (0, None),
        "avg_monthly_minutes": (0, None),
        "num_support_tickets": (0, None),
        "num_additional_services": (0, None)
    }

    for col, (min_val, max_val) in checks.items():
        invalid = df[col].isna()

        if min_val is not None:
            invalid |= df[col] < min_val

        if max_val is not None:
            invalid |= df[col] > max_val

        print(f"{col:<30} Invalid Rows : {invalid.sum()}")


check_numeric_ranges(df)

age                            Invalid Rows : 19
tenure_months                  Invalid Rows : 16
monthly_charges                Invalid Rows : 15
total_charges                  Invalid Rows : 23
avg_monthly_gb_used            Invalid Rows : 26
avg_monthly_minutes            Invalid Rows : 82
num_support_tickets            Invalid Rows : 7
num_additional_services        Invalid Rows : 0

In [11]:
df[df["total_charges"] < df["monthly_charges"]]

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,avg_monthly_gb_used,num_support_tickets,avg_monthly_minutes,satisfaction_score,payment_method,num_additional_services,last_interaction_date,churned
10,TC-002946,24.784629,F,2.476210,Two year,30.42,8.06,DSL,No,8.86,0.0,160.9,7.0,Mailed check,3,2024-06-17,0
32,TC-000498,39.144920,Female,1.000000,Month-to-month,22.85,16.04,Fiber optic,Yes,18.85,3.0,428.3,6.7,Electronic check,0,2024-06-23,1
49,TC-000766,31.452354,Female,1.000000,Month-to-month,52.23,28.02,No,Yes,4.20,4.0,337.1,3.5,Mailed check,2,2024-06-14,1
73,TC-000562,73.131012,Female,1.339115,Two year,62.12,47.61,DSL,Yes,23.88,0.0,427.0,3.9,Credit card,1,2024-03-21,1
81,TC-004115,66.444632,Female,1.882754,Two year,15.00,13.73,No,Yes,4.56,0.0,327.2,5.4,Credit card,4,2024-06-30,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4975,TC-000879,41.753657,F,1.330084,Month-to-month,44.56,6.38,NaN,Yes,10.67,2.0,285.7,6.4,bank transfer,1,2024-02-20,1
4993,TC-003074,66.477853,Female,1.000000,Month-to-month,68.56,34.12,DSL,Yes,34.68,1.0,492.8,3.7,Electronic check,2,2024-05-25,1
5035,TC-004556,37.493011,Female,1.164030,Two year,62.61,23.41,DSL,no,10.60,2.0,187.4,6.4,Electronic check,1,2024-06-02,0
5042,TC-002920,1.000000,F,2.353029,One year,54.52,41.22,DSL,Yes,3.47,2.0,337.6,5.1,Bank transfer,5,2024-06-17,1
5045,TC-004427,47.255553,Female,4.109119,Month-to-month,25.54,10.77,DSL,Yes,22.89,0.0,398.9,5.8,Mailed check,1,2024-06-14,1

In [12]:
df[
    (df["tenure_months"] == 0) &
    (df["total_charges"] > 0)
]

Empty DataFrame
Columns: [customer_id, age, gender, tenure_months, contract_type, monthly_charges, total_charges, internet_service, phone_service, avg_monthly_gb_used, num_support_tickets, avg_monthly_minutes, satisfaction_score, payment_method, num_additional_services, last_interaction_date, churned]
Index: []

In [13]:
df[
    (df["tenure_months"] > 6) &
    (df["total_charges"] == 0)
]

Empty DataFrame
Columns: [customer_id, age, gender, tenure_months, contract_type, monthly_charges, total_charges, internet_service, phone_service, avg_monthly_gb_used, num_support_tickets, avg_monthly_minutes, satisfaction_score, payment_method, num_additional_services, last_interaction_date, churned]
Index: []

In [14]:
duplicate_ids.sort_values("customer_id")

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,avg_monthly_gb_used,num_support_tickets,avg_monthly_minutes,satisfaction_score,payment_method,num_additional_services,last_interaction_date,churned
2677,TC-000124,20.972234,Female,9.921419,Month-to-month,92.47,907.46,DSL,Y,46.540000,1.0,290.1,5.7,Electronic check,0,2024-03-27,0
3130,TC-000124,20.972234,Female,9.921419,Month-to-month,92.47,907.46,DSL,Y,46.540000,1.0,290.1,5.7,Electronic check,0,2024-03-27,0
4447,TC-000385,30.613010,Female,69.584358,Month-to-month,69.10,4757.33,Fiber optic,Yes,13.510000,3.0,52.3,5.5,Mailed check,0,2024-05-30,1
301,TC-000385,30.613010,Female,69.584358,Month-to-month,69.10,4757.33,Fiber optic,Yes,13.510000,3.0,52.3,5.5,Mailed check,0,2024-05-30,1
2904,TC-000519,43.489985,Male,3.332264,One year,24.93,145.19,NaN,Yes,28.650000,2.0,270.3,10.0,Electronic check,4,2024-06-01,0
1353,TC-000519,43.489985,Male,3.332264,One year,24.93,145.19,NaN,Yes,28.650000,2.0,270.3,10.0,Electronic check,4,2024-06-01,0
349,TC-000619,49.215138,Female,1.078365,Month-to-month,40.03,138.63,Fiber optic,N,1.520000,4.0,354.3,5.7,Electronic check,4,2024-06-30,0
1237,TC-000619,49.215138,Female,1.078365,Month-to-month,40.03,138.63,Fiber optic,N,1.520000,4.0,354.3,5.7,Electronic check,4,2024-06-30,0
3126,TC-000620,45.358260,MALE,11.027876,One year,31.20,237.00,DSL,No,1.020000,4.0,239.8,7.8,Credit card,3,2024-06-04,0
3328,TC-000620,45.358260,MALE,11.027876,One year,31.20,237.00,DSL,No,1.020000,4.0,239.8,7.8,Credit card,3,2024-06-04,0
2921,TC-000638,43.099770,Female,20.351424,Two year,16.87,180.37,Fiber optic,Yes,20.720000,1.0,419.3,8.6,Electronic check,5,2024-06-08,0
2352,TC-000638,43.099770,Female,20.351424,Two year,16.87,180.37,Fiber optic,Yes,20.720000,1.0,419.3,8.6,Electronic check,5,2024-06-08,0
3506,TC-000675,20.887325,Female,20.046935,Two year,99.82,2021.22,NaN,Y,6.830000,1.0,99.1,9.9,Credit card,1,2024-05-20,0
1186,TC-000675,20.887325,Female,20.046935,Two year,99.82,2021.22,NaN,Y,6.830000,1.0,99.1,9.9,Credit card,1,2024-05-20,0
1942,TC-000716,58.549528,Female,20.921661,Month-to-month,18.50,276.21,Fiber optic,yes,10.510000,2.0,364.0,10.7,Bank transfer,3,2024-06-25,0
3467,TC-000716,58.549528,Female,20.921661,Month-to-month,18.50,276.21,Fiber optic,yes,10.510000,2.0,364.0,10.7,Bank transfer,3,2024-06-25,0
3367,TC-000730,30.325429,Male,11.661407,One year,79.95,1020.54,No,Yes,20.070000,4.0,260.6,2.2,Bank transfer,3,2024-06-02,1
2019,TC-000730,30.325429,Male,11.661407,One year,79.95,1020.54,No,Yes,20.070000,4.0,260.6,2.2,Bank transfer,3,2024-06-02,1
4233,TC-000866,36.184477,female,NaN,Two year,48.95,NaN,No,yes,37.810000,2.0,400.5,8.1,Credit card,0,2024-06-14,0
1704,TC-000866,36.184477,female,NaN,Two year,48.95,NaN,No,yes,37.810000,2.0,400.5,8.1,Credit card,0,2024-06-14,0
2882,TC-000980,53.406220,Female,14.368624,Month-to-month,68.48,904.76,Fiber optic,Yes,5.870000,2.0,309.2,9.2,credit card,2,2024-06-27,1
2107,TC-000980,53.406220,Female,14.368624,Month-to-month,68.48,904.76,Fiber optic,Yes,5.870000,2.0,309.2,9.2,credit card,2,2024-06-27,1
2047,TC-000981,53.787002,Male,5.107438,Month-to-month,30.66,96.80,fiber,Yes,3.030000,4.0,444.0,6.2,Bank transfer,1,2024-06-27,1
4756,TC-000981,53.787002,Male,5.107438,Month-to-month,30.66,96.80,fiber,Yes,3.030000,4.0,444.0,6.2,Bank transfer,1,2024-06-27,1
1111,TC-001062,18.000000,Female,42.418592,Month-to-month,35.27,1495.77,DSL,Yes,6.490000,0.0,288.7,4.0,Credit card,2,2024-05-23,1
4003,TC-001062,18.000000,Female,42.418592,Month-to-month,35.27,1495.77,DSL,Yes,6.490000,0.0,288.7,4.0,Credit card,2,2024-05-23,1
2414,TC-001100,47.197327,Male,2.870557,One year,49.80,335.95,DSL,No,14.160000,0.0,272.8,5.0,Electronic check,4,2024-06-03,0
2512,TC-001100,47.197327,Male,2.870557,One year,49.80,335.95,DSL,No,14.160000,0.0,272.8,5.0,Electronic check,4,2024-06-03,0
34,TC-001145,39.403923,M,4.400608,Two year,74.25,320.27,No,Yes,3.350000,4.0,355.4,2.2,Electronic check,5,2024-06-06,0
427,TC-001145,39.403923,M,4.400608,Two year,74.25,320.27,No,Yes,3.350000,4.0,355.4,2.2,Electronic check,5,2024-06-06,0
4261,TC-001455,50.482645,female,36.572751,One year,128.80,4777.76,NaN,no,24.600000,3.0,287.6,6.0,Credit card,0,2024-06-16,1
1000,TC-001455,50.482645,female,36.572751,One year,128.80,4777.76,NaN,no,24.600000,3.0,287.6,6.0,Credit card,0,2024-06-16,1
1286,TC-001596,26.854039,F,4.752376,Month-to-month,55.68,249.45,No,No,3.220000,3.0,283.3,3.3,Credit card,5,2024-06-08,0
3066,TC-001596,26.854039,F,4.752376,Month-to-month,55.68,249.45,No,No,3.220000,3.0,283.3,3.3,Credit card,5,2024-06-08,0
333,TC-001770,50.272281,Male,3.527552,Month-to-month,84.32,33.24,DSL,No,9.140000,1.0,266.6,6.3,Electronic check,2,2024-04-26,0
1125,TC-001770,50.272281,Male,3.527552,Month-to-month,84.32,33.24,DSL,No,9.140000,1.0,266.6,6.3,Electronic check,2,2024-04-26,0
4615,TC-001798,30.059612,Female,38.592325,Two year,85.00,3098.57,Fiber optic,No,0.130000,1.0,451.2,9.1,Bank transfer,5,2024-06-05,0
3209,TC-001798,30.059612,Female,38.592325,Two year,85.00,3098.57,Fiber optic,No,0.130000,1.0,451.2,9.1,Bank transfer,5,2024-06-05,0
853,TC-001809,18.282139,Male,47.940945,One year,21.44,965.99,fiber,N,20.000000,4.0,370.3,8.6,Bank transfer,3,2024-05-28,0
2474,TC-001809,18.282139,Male,47.940945,One year,21.44,965.99,fiber,N,20.000000,4.0,370.3,8.6,Bank transfer,3,2024-05-28,0
3720,TC-001877,33.567480,Male,18.035090,Month-to-month,85.16,1486.15,Fiber optic,Yes,3.180000,3.0,233.8,4.9,Credit card,4,2024-06-07,1
580,TC-001877,33.567480,Male,18.035090,Month-to-month,85.16,1486.15,Fiber optic,Yes,3.180000,3.0,233.8,4.9,Credit card,4,2024-06-07,1
3978,TC-001891,50.194264,male,14.728703,Month-to-month,48.27,851.61,Fiber optic,no,8.180000,4.0,71.9,3.9,CC,4,2024-06-22,0
1520,TC-001891,50.194264,male,14.728703,Month-to-month,48.27,851.61,Fiber optic,no,8.180000,4.0,71.9,3.9,CC,4,2024-06-22,0
577,TC-002054,37.444110,Female,4.038543,Month-to-month,29.80,119.12,fiber,Yes,-45.861245,1.0,455.7,7.8,Electronic check,0,2024-05-10,1
4917,TC-002054,37.444110,Female,4.038543,Month-to-month,29.80,119.12,fiber,Yes,-45.861245,1.0,455.7,7.8,Electronic check,0,2024-05-10,1
1914,TC-002424,41.347846,Male,23.696196,Month-to-month,39.64,970.31,DSL,No,20.530000,1.0,301.0,4.8,bank transfer,3,2024-05-17,1
4176,TC-002424,41.347846,Male,23.696196,Month-to-month,39.64,970.31,DSL,No,20.530000,1.0,301.0,4.8,bank transfer,3,2024-05-17,1
3120,TC-002570,38.480691,Female,10.912205,Two year,55.54,551.98,NaN,No,52.770000,1.0,135.0,9.3,Electronic check,4,2024-06-28,0
2053,TC-002570,38.480691,Female,10.912205,Two year,55.54,551.98,NaN,No,52.770000,1.0,135.0,9.3,Electronic check,4,2024-06-28,0
3224,TC-002580,68.379307,Female,21.649783,Month-to-month,15.03,355.28,Fiber optic,Yes,5.650000,2.0,299.3,0.8,Electronic check,2,2024-06-10,0
4769,TC-002580,68.379307,Female,21.649783,Month-to-month,15.03,355.28,Fiber optic,Yes,5.650000,2.0,299.3,0.8,Electronic check,2,2024-06-10,0
3137,TC-002668,23.512150,M,39.177810,Two year,76.08,2976.65,No,Yes,14.550000,1.0,14.4,5.0,Credit card,0,2024-06-10,1
3762,TC-002668,23.512150,M,39.177810,Two year,76.08,2976.65,No,Yes,14.550000,1.0,14.4,5.0,Credit card,0,2024-06-10,1
4948,TC-002732,67.275214,F,7.369903,Month-to-month,52.86,570.07,NaN,Yes,14.590000,2.0,198.3,5.2,Credit card,0,2024-06-29,1
627,TC-002732,67.275214,F,7.369903,Month-to-month,52.86,570.07,NaN,Yes,14.590000,2.0,198.3,5.2,Credit card,0,2024-06-29,1
4844,TC-002763,55.430331,Female,3.303473,One year,120.29,404.02,Fiber optic,Yes,0.240000,0.0,424.1,3.1,Credit card,0,2024-06-03,0
4287,TC-002763,55.430331,Female,3.303473,One year,120.29,404.02,Fiber optic,Yes,0.240000,0.0,424.1,3.1,Credit card,0,2024-06-03,0
1113,TC-002768,48.821114,Male,34.192009,Month-to-month,19.10,699.73,DSL,No,4.480000,0.0,476.7,4.1,Credit card,2,2024-05-15,1
2375,TC-002768,48.821114,Male,34.192009,Month-to-month,19.10,699.73,DSL,No,4.480000,0.0,476.7,4.1,Credit card,2,2024-05-15,1
76,TC-002787,30.450059,Male,48.480751,One year,57.37,2784.99,Fiber optic,Yes,44.940000,2.0,118.9,6.8,Credit card,2,2024-02-26,0
4596,TC-002787,30.450059,Male,48.480751,One year,57.37,2784.99,Fiber optic,Yes,44.940000,2.0,118.9,6.8,Credit card,2,2024-02-26,0
4126,TC-002974,71.809140,Other,17.706198,Month-to-month,38.29,683.22,Fiber optic,Yes,7.850000,2.0,137.2,6.9,Bank transfer,3,2024-06-09,1
3706,TC-002974,71.809140,Other,17.706198,Month-to-month,38.29,683.22,Fiber optic,Yes,7.850000,2.0,137.2,6.9,Bank transfer,3,2024-06-09,1
862,TC-003067,68.323996,Male,7.676196,Month-to-month,33.85,120.13,NaN,yes,8.220000,1.0,86.1,3.8,Electronic check,4,2024-03-07,0
2983,TC-003067,68.323996,Male,7.676196,Month-to-month,33.85,120.13,NaN,yes,8.220000,1.0,86.1,3.8,Electronic check,4,2024-03-07,0
4779,TC-003068,42.276024,Male,15.065428,Month-to-month,59.76,946.07,Fiber optic,yes,31.550000,1.0,408.1,4.9,Electronic check,4,2024-04-07,0
4792,TC-003068,42.276024,Male,15.065428,Month-to-month,59.76,946.07,Fiber optic,yes,31.550000,1.0,408.1,4.9,Electronic check,4,2024-04-07,0
1431,TC-003134,64.424073,MALE,18.605900,Two year,71.08,1336.34,Fiber optic,Yes,2.510000,5.0,367.8,9.0,CC,2,2024-06-26,0
2084,TC-003134,64.424073,MALE,18.605900,Two year,71.08,1336.34,Fiber optic,Yes,2.510000,5.0,367.8,9.0,CC,2,2024-06-26,0
2268,TC-003204,61.182987,Male,16.041344,One year,36.13,703.50,dsl,No,5.500000,1.0,475.2,4.8,BT,5,2024-06-23,0
3763,TC-003204,61.182987,Male,16.041344,One year,36.13,703.50,dsl,No,5.500000,1.0,475.2,4.8,BT,5,2024-06-23,0
1412,TC-003254,57.871775,Female,44.393716,Month-to-month,68.75,3183.89,DSL,No,5.050000,2.0,374.6,5.9,CC,4,2024-06-24,0
1423,TC-003254,57.871775,Female,44.393716,Month-to-month,68.75,3183.89,DSL,No,5.050000,2.0,374.6,5.9,CC,4,2024-06-24,0
4588,TC-003441,44.182818,Female,41.056964,One year,41.58,1859.75,Fiber optic,Yes,9.210000,5.0,416.4,7.0,credit card,2,2024-06-13,0
4167,TC-003441,44.182818,Female,41.056964,One year,41.58,1859.75,Fiber optic,Yes,9.210000,5.0,416.4,7.0,credit card,2,2024-06-13,0
932,TC-003797,39.534972,Male,8.942140,Month-to-month,30.20,254.14,No,Yes,19.480000,3.0,482.7,5.7,Bank transfer,4,2024-06-15,0
3333,TC-003797,39.534972,Male,8.942140,Month-to-month,30.20,254.14,No,Yes,19.480000,3.0,482.7,5.7,Bank transfer,4,2024-06-15,0
3839,TC-003857,21.063162,Female,36.662181,Month-to-month,88.48,3408.38,DSL,No,7.330000,0.0,NaN,6.5,Bank transfer,0,2024-06-24,0
2063,TC-003857,21.063162,Female,36.662181,Month-to-month,88.48,3408.38,DSL,No,7.330000,0.0,NaN,6.5,Bank transfer,0,2024-06-24,0
2959,TC-003951,49.729415,Female,2.793184,One year,23.23,75.25,NaN,Yes,1.670000,1.0,288.3,3.7,Electronic check,1,2024-06-29,0
3247,TC-003951,49.729415,Female,2.793184,One year,23.23,75.25,NaN,Yes,1.670000,1.0,288.3,3.7,Electronic check,1,2024-06-29,0
4622,TC-003970,61.359667,male,49.093859,One year,81.35,4097.83,DSL,no,28.950000,4.0,NaN,5.7,Mailed check,5,2024-06-30,0
4754,TC-003970,61.359667,male,49.093859,One year,81.35,4097.83,DSL,no,28.950000,4.0,NaN,5.7,Mailed check,5,2024-06-30,0
3680,TC-004162,49.197406,Female,18.794998,Two year,47.71,857.18,Fiber optic,No,1.840000,7.0,287.4,6.9,Credit card,2,2024-06-04,0
1681,TC-004162,49.197406,Female,18.794998,Two year,47.71,857.18,Fiber optic,No,1.840000,7.0,287.4,6.9,Credit card,2,2024-06-04,0
4671,TC-004250,999.000000,female,94.471391,Month-to-month,62.84,6126.25,NaN,Yes,15.420000,2.0,382.0,3.6,Credit card,0,2024-05-18,0
805,TC-004250,999.000000,female,94.471391,Month-to-month,62.84,6126.25,NaN,Yes,15.420000,2.0,382.0,3.6,Credit card,0,2024-05-18,0
4157,TC-004405,40.122384,MALE,1.187489,Month-to-month,74.86,29.58,fiber,Yes,15.010000,1.0,245.0,7.4,BT,2,2024-06-14,0
2691,TC-004405,40.122384,MALE,1.187489,Month-to-month,74.86,29.58,fiber,Yes,15.010000,1.0,245.0,7.4,BT,2,2024-06-14,0
2879,TC-004470,47.810572,male,5.693895,One year,21.26,37.04,Fiber optic,Yes,9.080000,2.0,307.2,4.7,Credit card,5,2024-06-20,0
3226,TC-004470,47.810572,male,5.693895,One year,21.26,37.04,Fiber optic,Yes,9.080000,2.0,307.2,4.7,Credit card,5,2024-06-20,0
0,TC-004711,32.874739,Male,10.149619,Month-to-month,69.24,656.42,DSL,Yes,11.700000,4.0,324.0,7.8,bank transfer,2,2024-06-14,1
2087,TC-004711,32.874739,Male,10.149619,Month-to-month,69.24,656.42,DSL,Yes,11.700000,4.0,324.0,7.8,bank transfer,2,2024-06-14,1
2306,TC-004745,66.065087,Female,83.041357,One year,15.00,1193.04,dsl,No,9.760000,2.0,279.1,6.8,Bank transfer,3,2024-06-14,0
4905,TC-004745,66.065087,Female,83.041357,One year,15.00,1193.04,dsl,No,9.760000,2.0,279.1,6.8,Bank transfer,3,2024-06-14,0
1080,TC-004920,61.391179,Male,20.090412,One year,92.52,1825.87,Fiber optic,No,19.960000,2.0,435.5,4.2,Credit card,0,2024-06-11,0
2789,TC-004920,61.391179,Male,20.090412,One year,92.52,1825.87,Fiber optic,No,19.960000,2.0,435.5,4.2,Credit card,0,2024-06-11,0
204,TC-004940,20.998939,Male,20.145723,Month-to-month,65.60,1447.34,No,Y,7.100000,2.0,271.1,2.6,Credit card,3,2024-05-26,0
2534,TC-004940,20.998939,Male,20.145723,Month-to-month,65.60,1447.34,No,Y,7.100000,2.0,271.1,2.6,Credit card,3,2024-05-26,0

In [15]:
df["last_interaction_date"] = pd.to_datetime(
    df["last_interaction_date"],
    errors="coerce"
)

print(df["last_interaction_date"].isna().sum())

0

In [16]:
df[df["last_interaction_date"] > pd.Timestamp.today()]

Empty DataFrame
Columns: [customer_id, age, gender, tenure_months, contract_type, monthly_charges, total_charges, internet_service, phone_service, avg_monthly_gb_used, num_support_tickets, avg_monthly_minutes, satisfaction_score, payment_method, num_additional_services, last_interaction_date, churned]
Index: []

In [17]:
quality_report = []

quality_report.append({
    "Issue": "Missing Values",
    "Status": "",
    "Rows Affected": "",
    "Cleaning Strategy": ""
})

quality_report.append({
    "Issue": "Duplicate Rows",
    "Status": "",
    "Rows Affected": "",
    "Cleaning Strategy": ""
})

quality_df = pd.DataFrame(quality_report)

quality_df

            Issue Status Rows Affected Cleaning Strategy
0  Missing Values
1  Duplicate Rows

## Data Cleaning

In [18]:
df_clean = df.copy()

In [19]:
df_clean.replace(r'^\s*$', np.nan, regex=True, inplace=True)

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,avg_monthly_gb_used,num_support_tickets,avg_monthly_minutes,satisfaction_score,payment_method,num_additional_services,last_interaction_date,churned
0,TC-004711,32.874739,Male,10.149619,Month-to-month,69.24,656.42,DSL,Yes,11.70,4.0,324.0,7.8,bank transfer,2,2024-06-14,1
1,TC-000692,59.389947,Female,3.446551,Month-to-month,98.48,251.15,DSL,no,9.46,1.0,306.8,6.0,Electronic check,5,2024-06-23,1
2,TC-000066,62.343600,male,1.386582,Two year,94.35,120.78,Fiber optic,Yes,9.56,4.0,349.5,5.5,Bank transfer,0,2024-06-21,0
3,TC-003427,45.788533,Female,67.609659,Month-to-month,85.87,5834.73,Fiber optic,yes,3.15,1.0,258.2,4.7,Credit card,4,2024-06-21,1
4,TC-004821,39.625418,F,27.319623,One year,62.14,1626.23,DSL,Yes,28.80,0.0,335.8,12.3,Credit card,2,2024-06-19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,TC-004427,47.255553,Female,4.109119,Month-to-month,25.54,10.77,DSL,Yes,22.89,0.0,398.9,5.8,Mailed check,1,2024-06-14,1
5046,TC-000467,51.212501,Male,42.018968,Month-to-month,73.19,3129.93,fiber,No,6.39,0.0,179.5,5.9,Credit card,0,2024-06-30,1
5047,TC-003093,40.583119,Male,28.176312,Month-to-month,56.55,1583.86,Fiber optic,Yes,20.79,2.0,371.3,5.0,Credit card,3,2024-06-18,1
5048,TC-003773,30.269948,M,2.730218,Month-to-month,64.79,448.34,Fiber optic,Yes,5.88,0.0,234.2,5.7,CC,4,2024-06-10,1
5049,TC-000861,45.043845,female,10.465199,One year,52.27,686.56,fiber,Yes,15.94,2.0,328.6,3.5,Credit card,5,2024-05-26,0

In [20]:
phone_mapping = {
    "Y": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    "y": "Yes",

    "N": "No",
    "NO": "No",
    "no": "No",
    "n": "No"
}

df_clean["phone_service"] = (
    df_clean["phone_service"]
        .astype(str)
        .str.strip()
        .replace(phone_mapping)
)

In [21]:
df_clean["phone_service"].value_counts(dropna=False)

phone_service
Yes    3205
No     1845
Name: count, dtype: int64

In [22]:
df_clean["age"].dropna().head(20)
df_clean["age"] = df_clean["age"].round().astype("Int64")

In [23]:
print(df_clean["satisfaction_score"].min())
print(df_clean["satisfaction_score"].max())

df_clean["satisfaction_score"].value_counts().sort_index()

-1.4
99.0

satisfaction_score
-1.4     2
-1.1     1
-1.0     5
-0.8     1
-0.7     1
        ..
 12.3    1
 12.9    1
 13.0    1
 15.0    1
 99.0    4
Name: count, Length: 130, dtype: int64

In [24]:
df_clean.loc[
    ~df_clean["satisfaction_score"].between(1, 5),
    "satisfaction_score"
] = np.nan

In [25]:
df_clean["last_interaction_date"] = pd.to_datetime(
    df_clean["last_interaction_date"],
    errors="coerce"
)

In [26]:
missing_after = pd.DataFrame({
    "Missing Count": df_clean.isnull().sum(),
    "Missing %": round(
        df_clean.isnull().sum() / len(df_clean) * 100,
        2
    )
})

missing_after[missing_after["Missing Count"] > 0]

                     Missing Count  Missing %
age                             10       0.20
gender                          50       0.99
tenure_months                   11       0.22
monthly_charges                 12       0.24
total_charges                   23       0.46
internet_service               505      10.00
avg_monthly_gb_used             15       0.30
avg_monthly_minutes             82       1.62
satisfaction_score            3475      68.81
payment_method                  30       0.59

In [27]:
df_clean["satisfaction_score"].describe()

count    1575.000000
mean        3.828190
std         0.918893
min         1.000000
25%         3.200000
50%         4.000000
75%         4.600000
max         5.000000
Name: satisfaction_score, dtype: float64

In [28]:
df_clean[
    df_clean["satisfaction_score"].between(1, 5)
].shape

(1575, 17)

In [29]:
df_clean[
    df_clean["satisfaction_score"].between(1, 10)
].shape

(1575, 17)

In [30]:
df_clean.loc[
    ~df_clean["satisfaction_score"].between(1, 5),
    "satisfaction_score"
] = np.nan

In [31]:
df_clean["total_charges"].describe()

count      5027.000000
mean       1642.319540
std        4183.374844
min           0.660000
25%         372.280000
50%         953.640000
75%        2122.525000
max      218681.580000
Name: total_charges, dtype: float64

In [32]:
df_clean[df_clean["total_charges"] < 0]

Empty DataFrame
Columns: [customer_id, age, gender, tenure_months, contract_type, monthly_charges, total_charges, internet_service, phone_service, avg_monthly_gb_used, num_support_tickets, avg_monthly_minutes, satisfaction_score, payment_method, num_additional_services, last_interaction_date, churned]
Index: []

In [33]:
df_clean[
    df_clean["total_charges"] < df_clean["monthly_charges"]
]

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,avg_monthly_gb_used,num_support_tickets,avg_monthly_minutes,satisfaction_score,payment_method,num_additional_services,last_interaction_date,churned
10,TC-002946,25,F,2.476210,Two year,30.42,8.06,DSL,No,8.86,0.0,160.9,NaN,Mailed check,3,2024-06-17,0
32,TC-000498,39,Female,1.000000,Month-to-month,22.85,16.04,Fiber optic,Yes,18.85,3.0,428.3,NaN,Electronic check,0,2024-06-23,1
49,TC-000766,31,Female,1.000000,Month-to-month,52.23,28.02,No,Yes,4.20,4.0,337.1,3.5,Mailed check,2,2024-06-14,1
73,TC-000562,73,Female,1.339115,Two year,62.12,47.61,DSL,Yes,23.88,0.0,427.0,3.9,Credit card,1,2024-03-21,1
81,TC-004115,66,Female,1.882754,Two year,15.00,13.73,No,Yes,4.56,0.0,327.2,NaN,Credit card,4,2024-06-30,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4975,TC-000879,42,F,1.330084,Month-to-month,44.56,6.38,NaN,Yes,10.67,2.0,285.7,NaN,bank transfer,1,2024-02-20,1
4993,TC-003074,66,Female,1.000000,Month-to-month,68.56,34.12,DSL,Yes,34.68,1.0,492.8,3.7,Electronic check,2,2024-05-25,1
5035,TC-004556,37,Female,1.164030,Two year,62.61,23.41,DSL,No,10.60,2.0,187.4,NaN,Electronic check,1,2024-06-02,0
5042,TC-002920,1,F,2.353029,One year,54.52,41.22,DSL,Yes,3.47,2.0,337.6,NaN,Bank transfer,5,2024-06-17,1
5045,TC-004427,47,Female,4.109119,Month-to-month,25.54,10.77,DSL,Yes,22.89,0.0,398.9,NaN,Mailed check,1,2024-06-14,1

In [34]:
quality_summary = pd.DataFrame([
    {
        "Column": "age",
        "Issue": "Missing values",
        "Rows Affected": df_clean["age"].isna().sum(),
        "Cleaning Strategy": "Median Imputation",
        "Reason": "Age distribution is often skewed and median is robust to outliers."
    },
    {
        "Column": "phone_service",
        "Issue": "Inconsistent categorical values",
        "Rows Affected": "Multiple",
        "Cleaning Strategy": "Standardized to Yes/No",
        "Reason": "Ensures consistent encoding before modeling."
    },
    {
        "Column": "satisfaction_score",
        "Issue": "Invalid values outside business range",
        "Rows Affected": (
            (~df_clean["satisfaction_score"].between(1,5)).sum()
        ),
        "Cleaning Strategy": "Replace invalid values with NaN, then impute median",
        "Reason": "Invalid scores likely represent data entry errors or sentinel values."
    }
])

quality_summary

,Column,Issue,Rows Affected,Cleaning Strategy,Reason
0,age,Missing values,10,Median Imputation,Age distribution is often skewed and median is...
1,phone_service,Inconsistent categorical values,Multiple,Standardized to Yes/No,Ensures consistent encoding before modeling.
2,satisfaction_score,Invalid values outside business range,3475,"Replace invalid values with NaN, then impute m...",Invalid scores likely represent data entry err...

In [35]:
numeric_cols = df_clean.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].median(), inplace=True)

In [36]:
categorical_cols = df_clean.select_dtypes(include="object").columns

for col in categorical_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

In [37]:
print("Missing Values:")
print(df_clean.isnull().sum())

print("\nDuplicate Rows:")
print(df_clean.duplicated().sum())

print("\nShape:")
print(df_clean.shape)

Missing Values:
customer_id                   0
age                          10
gender                       50
tenure_months                11
contract_type                 0
monthly_charges              12
total_charges                23
internet_service            505
phone_service                 0
avg_monthly_gb_used          15
num_support_tickets           0
avg_monthly_minutes          82
satisfaction_score         3475
payment_method               30
num_additional_services       0
last_interaction_date         0
churned                       0
dtype: int64

Duplicate Rows:
50

Shape:
(5050, 17)

In [38]:
before_after = pd.DataFrame({
    "Before": df.isnull().sum(),
    "After": df_clean.isnull().sum()
})

before_after = before_after[
    (before_after["Before"] > 0) |
    (before_after["After"] > 0)
]

before_after

                     Before  After
age                      10     10
gender                   50     50
tenure_months            11     11
monthly_charges          12     12
total_charges            23     23
internet_service        505    505
avg_monthly_gb_used      15     15
avg_monthly_minutes      82     82
satisfaction_score       20   3475
payment_method           30     30

In [39]:
df_clean.to_csv("../dataset/cleaned_data.csv", index=False)